apriltag:                 # node name
  ros__parameters:
    # setup (defaults)
    image_transport: raw  # image format: "raw" or "compressed"
    family: 36h11         # tag family name: 16h5, 25h9, 36h11
    size: 0.135 #0.2032             # default tag edge size in meter
    profile: false        # print profiling information to stdout
    image_rect: /image_raw 
    camera_info: /camera_info

    # tuning of detection (defaults)
    max_hamming: 3        # maximum allowed hamming distance (corrected bits)
    detector:
      threads: 3          # number of threads
      decimate: 2.0       # decimate resolution for quad detection
      blur: 0.0           # sigma of Gaussian blur for quad detection
      refine: 1           # snap to strong gradients
      sharpening: 0.25    # sharpening of decoded images
      debug: 0            # write additional debugging images to current working directory

    # (optional) list of tags
    # If defined, 'frames' and 'sizes' must have the same length as 'ids'.
    tag:
      ids:    [7, 5, 6 ]        # tag IDs for which to publish transform
      frames: [Ground, Monica, Ross]   # frame names
      sizes:  [0.17145, 0.135, 0.135]     # tag-specific edge size, overrides the default 'size'
