/**:
    ros__parameters:
        image_transport: raw    # image format
        family: 36h11           # tag family name
        size: 0.173             # tag edge size in meter
        max_hamming: 2         # maximum allowed hamming distance (corrected bits)

        # see "apriltag.h" 'struct apriltag_detector' for more documentation on these optional parameters
        detector:
            threads: 4          # number of threads
            decimate: 1.0       # decimate resolution for quad detection
            blur: 1.0           # sigma of Gaussian blur for quad detection
            refine: True        # snap to strong gradients
            sharpening: 0.25    # sharpening of decoded images
            debug: False        # write additional debugging images to current working directory

        # optional list of tags
        tag:
            ids:    [7, 6, 12, 8, 13, 10]        # tag IDs for which to publish transform
            frames: [ground, monica, monica/mast_link, ross, ross/mast_link, payload]   # frame names
            sizes:  [0.166, 0.166, 0.166, 0.166, 0.166, 0.166]     # tag-specific edge size, overrides the default 'size'


