/**/admittance_controller_node:
  ros__parameters:
    mass:       5.0
    damping:   45.0
    stiffness: 95.0

/**/virtual_pose_publisher_node:
  ros__parameters:
    frequency: 0.002
    x_pos:     0.0
    y_pos:     0.250
    z_pos:     0.1
    x:         0.0
    y:         0.0
    z:         0.707
    w:         0.707

/**/force_publisher_node:
  ros__parameters:
    delay:     0.0
    frequency: 0.002
    max_ticks: 2500
    duration:  120.0 # in seconds