name: arm_controller_domain_bridge
from_domain: 44
to_domain: 42
topics:
  ross/px100_virtual_pose_updater:
    type: std_msgs/msg/Float64
    from_domain: 44
    to_domain: 42
  
  monica/px100_virtual_pose_updater:
    type: std_msgs/msg/Float64
    from_domain: 44
    to_domain: 43