/**/:
  rtabmap:
    ros__parameters:
      use_sim_time: true
      frame_id: base_footprint
      # doesn't exist for rtabmap slam nodes
      # odom_frame_id: odom
      map_frame_id: map
      wait_imu_to_init: true
      subscribe_depth: false
      subscribe_rgb: true
      subscribe_odom_info: false
      
      publish_tf_odom: false


      approx_sync: true
      approx_sync_max_interval: 0.01

      RGBD/LinearUpdate: "0.0"
      RGBD/AngularUpdate: "0.0"

      Rtabmap/DetectionRate: "15.0"
      
      # Kp/MaxDepth: 4
      # Kp/MaxFeatures: 500

      # Vis/MaxFeatures: 600

      # Force RTAB to only map out (x, y, theta)
      # Reg/Force3DoF: true
      # RGBD/ForceOdom3DoF: true
      # Grid/3D: "false" # only create a 2D map

      # Vis/CorType: 1

      # IMU Madgwick parameters
      # ImuFilter/MadgwickGain: 0.03
      # ImuFilter/MadgwickZeta: 0.001
