/**/:
  slam_toolbox:
    ros__parameters:
      frame_id: base_footprint
      odom_frame_id: odom
      map_frame_id: map
      wait_imu_to_init: true
      subscribe_depth: true
      subscribe_odom_info: false
      
      publish_tf_odom: false


      approx_sync: true
      approx_sync_max_interval: 0.01

      RGBD/LinearUpdat: 0.0
      RGBD/AngularUpdate: 0.0

      Rtabmap/DetectionRate: 30.0
      
      Kp/MaxDepth: 4
      Kp/MaxFeatures: 200

      # Force RTAB to only map out (x, y, theta)
      Reg/Force3DoF: true
      Grid/3D: false # only create a 2D map
