/**/:
  slam_toolbox:
    ros__parameters:
      frame_id: base_link
      odom_frame_id: odom
      map_frame_id: map
      wait_imu_to_init: true
      subscribe_depth: true
      subscribe_odom_info: false
      
      publish_tf_odom: false


      approx_sync: false
      # approx_sync_max_interval: 0.01

      RGBD/LinearUpdat: 0.0
      RGBD/AngularUpdate: 0.0

      Rtabmap/DetectionRate: 30.0
      
      