/**:
  ros__parameters:
    camera_name: "ceiling_camera"
    frame_id:  "ceiling_camera"
    image_width: 800
    image_height: 448
    frame_rate: 30.0
    io_method: 'mmap'
    pixel_format: 'yuyv'
    camera_info_url: "package://mariam_demos/resource/ceiling_camera_y.yaml"
    camera_frame_id: "ceiling_camera"
    device: '/dev/video_ceiling'

