# joy node mappings
- name: joy
  namespace: /
  remapping:
    - from: /sensor_msgs/msg/Joy
      to:
        - domain: 1
        - domain: 2

# goal_pose_joy node mappings
- name: goal_pose_joy
  namespace: /
  remapping:
    - from: /visualization_msgs/msg/Marker
      to: 
        - domain: 0
      remap:
        - from: /visualization_msgs/msg/Marker
          to: /monica/goal_pose_joy
        - from: /visualization_msgs/msg/Marker
          to: /ross/goal_pose_joy

# px100/joint_states node mappings
- name: px100/joint_states
  namespace: /
  remapping:
    - from: /sensor_msgs/msg/JointState
      to: 
        - domain: 0
      remap:
        - from: /sensor_msgs/msg/JointState
          to: /monica/joint_states
        - from: /sensor_msgs/msg/JointState
          to: /ross/joint_states
