ekf_filter_node:
  ros__parameters:
    frequency: 30.0  # Frequency of the filter's update loop
    sensor_timeout: 0.1  # Sensor data timeout in seconds

    # Specify the map and odom frames
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link

    # Whether to publish TF transforms
    publish_tf: true
    tf_publish_frequency: 50.0

    # Inputs
    use_control: false  # Not using control inputs in this case
    odom0: /ross/wheel/odom
    odom0_config: [true, true, false,  # x, y, z
                   false, false, true,  # roll, pitch, yaw
                   false, false, false,  # vx, vy, vz
                   false, false, false]  # vroll, vpitch, vyaw
    odom0_differential: false
    odom0_relative: false

    imu0: /ross/camera/camera/imu
    imu0_config: [false, false, false,  # x, y, z
                  true, true, true,  # roll, pitch, yaw
                  false, false, false,  # vx, vy, vz
                  true, true, true]  # vroll, vpitch, vyaw
    imu0_differential: true
    imu0_relative: true

    # Process noise (adjust these values based on tuning)
    process_noise_covariance: [0.1, 0.0, 0.0, 0.0, 0.0, 0.0,
                           0.0, 0.1, 0.0, 0.0, 0.0, 0.0,
                           0.0, 0.0, 0.1, 0.0, 0.0, 0.0,
                           0.0, 0.0, 0.0, 0.1, 0.0, 0.0,
                           0.0, 0.0, 0.0, 0.0, 0.1, 0.0,
                           0.0, 0.0, 0.0, 0.0, 0.0, 0.1]


    # IMU bias covariance
    imu0_remove_gravitational_acceleration: true
    initial_estimate_covariance: [1e-9, 0.0, 0.0, 0.0, 0.0, 0.0,
                              0.0, 1e-9, 0.0, 0.0, 0.0, 0.0,
                              0.0, 0.0, 1e-9, 0.0, 0.0, 0.0,
                              0.0, 0.0, 0.0, 1e-9, 0.0, 0.0,
                              0.0, 0.0, 0.0, 0.0, 1e-9, 0.0,
                              0.0, 0.0, 0.0, 0.0, 0.0, 1e-9]

